### PR TITLE
Update cron time, minor workflow name changes

### PR DESCRIPTION
**Pull request by mwengren**
Some nit-picky name changes and changed cron time to 1400 UTC

### CODE REVIEW

**Comment by mwengren** [comment]
Hey @MathewBiddle If this looks ok, pls squash and merge this.  Thx!

**Review by MathewBiddle — APPROVED** [review]
Looks good

**Comment by MathewBiddle** [comment]
My first squash and merge! 🎉

**Comment by mwengren** [comment]
It makes for a cleaner commit history.  Merge commits probably not necessary for simple changes like this anyway.  Thx!

**Pull request merged**
