### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by emiliom**

### CODE REVIEW

**Comment by mwengren** [comment]
@emiliom Do you want us to merge this?  Were you trying to make a pull request on a downstream copy of this template/skeleton repo?

**Comment by emiliom** [comment]
@mwengren Actually, scratch this (don't merge)!

@jbosch-noaa and I were on the phone when I tried making a change to the place holder "home" page for the [new repo](https://github.com/ioos/BioData-Training-Workshop) that's reflected at https://ioos.github.io/BioData-Training-Workshop/ While we were talking I clicked on the "Edit Me" button near the top, and made a trivial change just to test my permissions. I didn't notice until now that the link took me to the template Jekyll page, not the corresponding version of the file on our new workshop repo!

I've now tested my permission to edit a page on the workshop repo (https://github.com/ioos/BioData-Training-Workshop/blob/gh-pages/_docs/index.md), and it worked as expected. Great.

Sorry for the confusion, and thanks for your help.

**Comment by mwengren** [comment]
@emiliom @jbosch-noaa

Yes, there are a few path/config settings to be changed in the [_config.yml file](https://github.com/ioos/BioData-Training-Workshop/blob/gh-pages/_config.yml) in the downstream repos.  The GitHub editme path is one, which should point to the downstream repo location and not the template repo.

I'm not sure if these steps are in @abirger instructions, but we should consider adding them if not, so folks know exactly what needs to be changed from the skeleton so the resulting site is properly configured.

**Comment by abirger** [comment]
@mwengren , I had set the URLs in the `_config.yml` file to these values because otherwise Jekyll wouldn't render the pages. I should've changed them when I pushed the `skeleton` to GitHub but obviously forgot to do that. Sorry for the confusion.
To avoid further confusion, I will change the URLs to some non-routable ones right away; perhaps, some change in the guide is also necessary.

P.S. It seems that I did not forget to change the URLs, but rather relied on the disclaimer in the comment line saying that the URL has to be replaced 'ioos-documentation-jekyll-skeleton' with your GitHub repo name. Obviously, it was super-optimistic, and I should've replaced the URLs...

**Comment by emiliom** [comment]
FYI, I haven't tried following the actual instructions yet. I'll do that by tomorrow and report back at least to @abirger and @jbosch-noaa

Like I said, this particular goof was due to me just clicking on a default link on the default, place-holder home /index page, while being distracted.

**Comment by abirger** [comment]
@emiliom, that URL is pre-configured for Jekyll rendering the website, so it has to be changed before the repo gets pushed to GitHub. There was no goof on your side, I should've been more clear...

**Pull request closed without merging**
